/* Bilingual glossary: [topic id, English term, Indonesian term, English definition, Indonesian definition] */
const GLOSSARY = [
  ["place-value", "place value", "nilai tempat", "The value a digit has because of its position in a number, such as tens or hundreds.", "Nilai sebuah angka karena posisinya dalam bilangan, misalnya puluhan atau ratusan."],
  ["place-value", "rounding", "pembulatan", "Replacing a number by a nearby simpler one, for example to the nearest ten.", "Mengganti bilangan dengan bilangan terdekat yang lebih sederhana, misalnya ke puluhan terdekat."],
  ["add-sub", "sum", "jumlah", "The result of adding numbers.", "Hasil penjumlahan bilangan-bilangan."],
  ["add-sub", "difference", "selisih", "The result of subtracting one number from another.", "Hasil pengurangan satu bilangan dari bilangan lain."],
  ["mul-div", "product", "hasil kali", "The result of multiplying numbers.", "Hasil perkalian bilangan-bilangan."],
  ["mul-div", "quotient", "hasil bagi", "The result of dividing one number by another.", "Hasil pembagian satu bilangan oleh bilangan lain."],
  ["mul-div", "remainder", "sisa", "What is left over when a number does not divide exactly.", "Bagian yang tersisa ketika pembagian tidak habis."],
  ["order-ops", "order of operations", "urutan operasi hitung", "The agreed order for working out an expression: brackets, powers, × and ÷, then + and −.", "Urutan yang disepakati untuk menghitung: kurung, pangkat, × dan ÷, lalu + dan −."],
  ["factors", "factor", "faktor", "A whole number that divides another number exactly.", "Bilangan bulat yang membagi habis bilangan lain."],
  ["factors", "multiple", "kelipatan", "The result of multiplying a number by a whole number.", "Hasil perkalian suatu bilangan dengan bilangan bulat."],
  ["factors", "prime number", "bilangan prima", "A whole number greater than 1 whose only factors are 1 and itself.", "Bilangan bulat lebih dari 1 yang faktornya hanya 1 dan bilangan itu sendiri."],
  ["factors", "greatest common factor (GCF)", "faktor persekutuan terbesar (FPB)", "The largest number that divides two or more numbers exactly.", "Bilangan terbesar yang membagi habis dua bilangan atau lebih."],
  ["factors", "least common multiple (LCM)", "kelipatan persekutuan terkecil (KPK)", "The smallest number that is a multiple of two or more numbers.", "Bilangan terkecil yang merupakan kelipatan dua bilangan atau lebih."],
  ["fractions", "numerator", "pembilang", "The top number of a fraction: how many parts are taken.", "Angka di atas pada pecahan: banyaknya bagian yang diambil."],
  ["fractions", "denominator", "penyebut", "The bottom number of a fraction: how many equal parts make a whole.", "Angka di bawah pada pecahan: banyaknya bagian sama besar dalam satu utuh."],
  ["fractions", "equivalent fractions", "pecahan senilai", "Fractions that have the same value, such as 1/2 and 2/4.", "Pecahan-pecahan yang nilainya sama, misalnya 1/2 dan 2/4."],
  ["decimals", "decimal", "desimal", "A number written with a decimal point (or comma) to show tenths, hundredths and so on.", "Bilangan yang ditulis dengan tanda desimal untuk menyatakan persepuluhan, perseratusan, dan seterusnya."],
  ["percent", "percentage", "persentase", "A number of parts out of 100, written with the % sign.", "Banyaknya bagian dari 100, ditulis dengan tanda %."],
  ["perimeter-area", "perimeter", "keliling", "The total distance around the edge of a flat shape.", "Panjang seluruh batas di sekeliling bangun datar."],
  ["perimeter-area", "area", "luas", "The amount of flat surface a shape covers, measured in square units.", "Besar permukaan yang ditutupi suatu bangun, diukur dalam satuan persegi."],
  ["volume-basic", "volume", "volume", "The amount of space a solid takes up, measured in cubic units.", "Besar ruang yang ditempati bangun ruang, diukur dalam satuan kubik."],
  ["angles-shapes", "right angle", "sudut siku-siku", "An angle of exactly 90°.", "Sudut yang besarnya tepat 90°."],
  ["angles-shapes", "polygon", "segi banyak", "A closed flat shape with straight sides.", "Bangun datar tertutup yang sisinya berupa garis lurus."],
  ["data-basic", "mean", "rata-rata (mean)", "The sum of the values divided by how many values there are.", "Jumlah semua nilai dibagi banyaknya nilai."],
  ["data-basic", "median", "median", "The middle value when the data are put in order.", "Nilai tengah setelah data diurutkan."],
  ["data-basic", "mode", "modus", "The value that occurs most often.", "Nilai yang paling sering muncul."],
  ["integers", "integer", "bilangan bulat", "A whole number that can be positive, negative or zero.", "Bilangan tanpa pecahan yang bisa positif, negatif, atau nol."],
  ["exponents", "exponent (power)", "pangkat (eksponen)", "The small number that says how many times the base is multiplied by itself.", "Angka kecil yang menyatakan berapa kali bilangan pokok dikalikan dengan dirinya sendiri."],
  ["exponents", "square root", "akar kuadrat", "A number that gives the original number when multiplied by itself.", "Bilangan yang jika dikalikan dengan dirinya sendiri menghasilkan bilangan semula."],
  ["sci-notation", "scientific notation", "notasi ilmiah", "Writing a number as a × 10ⁿ with 1 ≤ a < 10.", "Menulis bilangan dalam bentuk a × 10ⁿ dengan 1 ≤ a < 10."],
  ["ratio", "ratio", "perbandingan (rasio)", "A comparison of two quantities, written like 2 : 3.", "Perbandingan dua besaran, ditulis seperti 2 : 3."],
  ["ratio", "proportion", "proporsi", "A statement that two ratios are equal.", "Pernyataan bahwa dua perbandingan bernilai sama."],
  ["algebra-expr", "variable", "variabel", "A letter that stands for an unknown or changing number.", "Huruf yang mewakili bilangan yang belum diketahui atau berubah-ubah."],
  ["algebra-expr", "coefficient", "koefisien", "The number multiplying a variable, such as 3 in 3x.", "Bilangan yang mengalikan variabel, misalnya 3 pada 3x."],
  ["algebra-expr", "like terms", "suku sejenis", "Terms with the same variables and powers, which can be added together.", "Suku-suku dengan variabel dan pangkat yang sama, yang dapat dijumlahkan."],
  ["linear-eq", "equation", "persamaan", "A statement that two expressions are equal, with an = sign.", "Pernyataan bahwa dua bentuk bernilai sama, memakai tanda =."],
  ["inequalities", "inequality", "pertidaksamaan", "A statement that compares expressions with <, >, ≤ or ≥.", "Pernyataan yang membandingkan bentuk aljabar dengan <, >, ≤, atau ≥."],
  ["sets", "set", "himpunan", "A well-defined collection of objects, called elements.", "Kumpulan objek yang terdefinisi dengan jelas, disebut anggota."],
  ["sets", "intersection", "irisan", "The elements that belong to both sets (A ∩ B).", "Anggota yang termasuk dalam kedua himpunan (A ∩ B)."],
  ["sets", "union", "gabungan", "The elements that belong to at least one of the sets (A ∪ B).", "Anggota yang termasuk dalam sedikitnya satu himpunan (A ∪ B)."],
  ["linear-functions", "gradient (slope)", "gradien (kemiringan)", "How steep a line is: the change in y divided by the change in x.", "Kecuraman garis: perubahan y dibagi perubahan x."],
  ["linear-functions", "y-intercept", "titik potong sumbu y", "The point where a graph crosses the y-axis.", "Titik tempat grafik memotong sumbu y."],
  ["systems", "system of equations", "sistem persamaan", "Two or more equations that must be true at the same time.", "Dua persamaan atau lebih yang harus berlaku bersamaan."],
  ["pythagoras", "hypotenuse", "hipotenusa (sisi miring)", "The longest side of a right triangle, opposite the right angle.", "Sisi terpanjang segitiga siku-siku, di depan sudut siku-siku."],
  ["circles", "radius", "jari-jari", "The distance from the centre of a circle to its edge.", "Jarak dari pusat lingkaran ke tepinya."],
  ["circles", "circumference", "keliling lingkaran", "The distance around a circle, 2πr.", "Panjang di sekeliling lingkaran, 2πr."],
  ["statistics-jh", "range", "jangkauan", "The largest value minus the smallest value.", "Nilai terbesar dikurangi nilai terkecil."],
  ["probability-jh", "probability", "peluang", "A number from 0 to 1 that measures how likely an event is.", "Bilangan dari 0 sampai 1 yang mengukur seberapa mungkin suatu kejadian terjadi."],
  ["probability-jh", "sample space", "ruang sampel", "The set of all possible outcomes of an experiment.", "Himpunan semua hasil yang mungkin dari suatu percobaan."],
  ["similarity", "similar figures", "bangun sebangun", "Shapes with the same angles and proportional sides.", "Bangun-bangun dengan sudut yang sama dan sisi yang sebanding."],
  ["quadratics", "quadratic equation", "persamaan kuadrat", "An equation of the form ax² + bx + c = 0 with a ≠ 0.", "Persamaan berbentuk ax² + bx + c = 0 dengan a ≠ 0."],
  ["quadratics", "discriminant", "diskriminan", "The number b² − 4ac, which tells how many real roots a quadratic has.", "Bilangan b² − 4ac, yang menentukan banyaknya akar real persamaan kuadrat."],
  ["quad-functions", "parabola", "parabola", "The U-shaped graph of a quadratic function.", "Grafik berbentuk U dari fungsi kuadrat."],
  ["quad-functions", "vertex", "titik puncak", "The turning point of a parabola, its highest or lowest point.", "Titik balik parabola, yaitu titik tertinggi atau terendahnya."],
  ["functions", "function", "fungsi", "A rule that gives exactly one output for each input.", "Aturan yang memberi tepat satu keluaran untuk setiap masukan."],
  ["functions", "domain", "daerah asal (domain)", "The set of allowed inputs of a function.", "Himpunan masukan yang diperbolehkan pada suatu fungsi."],
  ["functions", "inverse function", "fungsi invers", "A function that undoes another function.", "Fungsi yang membalik kerja fungsi lain."],
  ["exp-log", "logarithm", "logaritma", "The power to which a base must be raised to give a number: log₂ 8 = 3.", "Pangkat yang diperlukan agar bilangan pokok menghasilkan suatu bilangan: ²log 8 = 3."],
  ["sequences", "arithmetic sequence", "barisan aritmetika", "A sequence with a constant difference between terms.", "Barisan dengan selisih tetap antara suku-sukunya."],
  ["sequences", "geometric sequence", "barisan geometri", "A sequence with a constant ratio between terms.", "Barisan dengan rasio tetap antara suku-sukunya."],
  ["trig-basics", "sine", "sinus", "In a right triangle, the opposite side divided by the hypotenuse.", "Pada segitiga siku-siku, sisi depan dibagi sisi miring."],
  ["trig-basics", "cosine", "kosinus", "In a right triangle, the adjacent side divided by the hypotenuse.", "Pada segitiga siku-siku, sisi samping dibagi sisi miring."],
  ["trig-basics", "radian", "radian", "The angle made by an arc as long as the radius; 180° = π radians.", "Sudut yang dibentuk busur sepanjang jari-jari; 180° = π radian."],
  ["polynomials", "polynomial", "polinomial (suku banyak)", "A sum of terms that are powers of x multiplied by numbers.", "Jumlah suku-suku berupa pangkat x yang dikalikan bilangan."],
  ["matrices", "matrix", "matriks", "A rectangular array of numbers arranged in rows and columns.", "Susunan bilangan berbentuk persegi panjang dalam baris dan kolom."],
  ["matrices", "determinant", "determinan", "A number calculated from a square matrix; the matrix has an inverse only if it is not zero.", "Bilangan yang dihitung dari matriks persegi; matriks punya invers hanya jika determinannya tidak nol."],
  ["vectors", "vector", "vektor", "A quantity with both size and direction.", "Besaran yang memiliki besar dan arah."],
  ["limits", "limit", "limit", "The value a function gets closer and closer to as x approaches a number.", "Nilai yang makin didekati fungsi ketika x mendekati suatu bilangan."],
  ["derivatives", "derivative", "turunan", "The rate of change of a function; the gradient of its graph at a point.", "Laju perubahan fungsi; gradien grafiknya di suatu titik."],
  ["integrals", "integral", "integral", "The reverse of differentiation; a definite integral gives the area under a curve.", "Kebalikan dari turunan; integral tentu memberi luas di bawah kurva."],
  ["combinatorics", "permutation", "permutasi", "An arrangement of objects where the order matters.", "Susunan objek yang memperhatikan urutan."],
  ["combinatorics", "combination", "kombinasi", "A selection of objects where the order does not matter.", "Pemilihan objek yang tidak memperhatikan urutan."],
  ["statistics-sh", "standard deviation", "simpangan baku", "A measure of how spread out the data are around the mean.", "Ukuran seberapa tersebar data di sekitar rata-rata."],
  ["logic", "implication", "implikasi", "A statement \"if p then q\", written p ⇒ q.", "Pernyataan \"jika p maka q\", ditulis p ⇒ q."],
  ["linear-programming", "objective function", "fungsi objektif (tujuan)", "The expression to be maximised or minimised in linear programming.", "Bentuk yang ingin dimaksimumkan atau diminimumkan dalam program linear."],
  ["series", "convergent series", "deret konvergen", "An infinite series whose sum approaches a finite value.", "Deret tak hingga yang jumlahnya mendekati suatu nilai berhingga."],
  ["ode", "differential equation", "persamaan diferensial", "An equation that involves a function and its derivatives.", "Persamaan yang memuat suatu fungsi dan turunan-turunannya."],
  ["linear-algebra", "eigenvalue", "nilai eigen", "A number λ with Av = λv for some non-zero vector v.", "Bilangan λ yang memenuhi Av = λv untuk suatu vektor v tak nol."],
  ["complex", "complex number", "bilangan kompleks", "A number a + bi, where i² = −1.", "Bilangan berbentuk a + bi, dengan i² = −1."],
  ["distributions", "normal distribution", "distribusi normal", "The symmetric, bell-shaped probability distribution.", "Distribusi peluang simetris yang berbentuk lonceng."],
  ["inference", "hypothesis test", "uji hipotesis", "A method for deciding from sample data whether to reject a claim about a population.", "Metode untuk memutuskan dari data sampel apakah suatu klaim tentang populasi ditolak."]
];
